export const MAKE_API_REQUEST_WITH_PARAMETERS = 'MAKE_API_REQUEST_WITH_PARAMETERS';



export const LOAD_NEW_BEER_DATA = 'LOAD_NEW_BEER_DATA';
export const DATA_WAS_NOT_FOUND = 'DATA_WAS_NOT_FOUND';


export const UPDATE_FILTER_STATE = 'UPDATE_FILTER_STATE';

export const RESET_PAGINATION = 'RESET_PAGINATION';
export const LOAD_NEXT_PAGE = 'LOAD_NEXT_PAGE';
export const LOAD_PREVIOUS_PAGE = 'LOAD_PREVIOUS_PAGE';
export const SHOW_NEXT_BUTTON = 'SHOW_NEXT_BUTTON';


export const SHOW_LOADING_INDICATOR = 'SHOW_LOADING_INDICATOR';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';


export const SHOW_RANDOM_BEER = 'SHOW_RANDOM_BEER';
export const HIDE_RANDOM_BEER = 'HIDE_RANDOM_BEER';